### ISSUE TITLE
v1.064 beta - Roman and Italic hyphens

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-font#195]
When I was checking the figuredash updates I noticed some weirdness with hyphens.

**/hyphen/nonbreakinghyphen/hyphen.sups**

### Roman

**/hyphen**
at Width axis min (75)
at Weight axis min (300) = 270 width
at Weight axis max (700) = 269 width 
So width stays the same (basically)
**/nonbreakinghyphen**
at Width axis min (75)
at Weight axis min (300) = 270 width
at Weight axis max (700) = **329 width**
Width increased with the Weight axis, and it no longer matches the hyphen width.
Same situation with other Width axis settings - the nobreakinghyphen is wider.
Should always be the same as hyphen.

Enlarge axis has no effect on Roman.

### Italic

**/hyphen**
at Width axis min (75)
at Weight axis min (300) = 339 width (?)
at Weight axis max (700) = 296 width (?)
So width goes down when increasing the Weight axis
**/nonbreakinghyphen**
at Width axis min (75)
at Weight axis min (300) = 339 width
at Weight axis max (700) = 296 width
Same, width goes down when increasing the Weight axis
But it is the same as the hyphen.
**/hyphen.sups**
at Width axis min (75)
at Weight axis min (300) = 308 width
at Weight axis def (400) = 245 width
at Weight axis max (700) = 277 width
So it goes down at Weight 400 then back up again. Odd.

Enlarge axis shifts these glyphs in the Italic.
Should have no effect.

**Comment by psb1558** [comment]
This is fixed. I'm going to do a few more things before I post new fonts.

**Comment by kenmcd** [comment]
Checked in v1.067 and appears to be one issue still.
In Roman...
/nonbreakinghyphen advance width increases with the Weight axis.

![2023-07-24_18-39-38](https://github.com/psb1558/Junicode-font/assets/844920/9c2caf4e-436c-4c1b-a253-14db15e5a082)

**Comment by psb1558** [comment]
I have fixed the problem with advance width of U+00AD.

**Comment by kenmcd** [comment]
Looks good. Closing.
